name: bubbles
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
  assets:
      - assets/bubbleImages/bubble.png
      - assets/bubbleImages/bubble6.png
      - assets/bubbleImages/bubble4.png
      - assets/bubbleImages/bubble5.png
      - assets/bubbleImages/bubble2.png
      - assets/bubbleImages/bubble3.png
      - assets/bubbleImages/bubbleIcon.png
      - assets/otherIcons/
